### ISSUE TITLE
not run

### ISSUE THREAD

**Issue by johnfelipe** [cdimascio/watson-html5-speech-recognition#1]
```
felipe@felipeurrego:~/watson-html5-speech-recognition/example/server$ npm start

> example@0.5.0 start /home/felipe/watson-html5-speech-recognition/example/server
> node app.js

module.js:327
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/felipe/watson-html5-speech-recognition/example/server/app.js:2:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

npm ERR! Linux 4.2.0-27-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! example@0.5.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the example@0.5.0 start script 'node app.js'.
npm ERR! This is most likely a problem with the example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs example
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/felipe/watson-html5-speech-recognition/example/server/npm-debug.log
felipe@felipeurrego:~/watson-html5-speech-recognition/example/server$ node app.js
module.js:327
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/felipe/watson-html5-speech-recognition/example/server/app.js:2:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

**Comment by cdimascio** [comment]
hi john felipe, looks like the instructions are not quite up to date. i'll have a look. in the meantime, you'll want to first run the steps under Setup the Example, followed by the steps in Run the Example
you'll notice that the directory in the README is incorrect. It should be 'example/server', not 'examples'

**Comment by cdimascio** [comment]
a new version has been published. The README has been updated as part of the change
